### PR TITLE
Tests: Configuration::ListParameter unit-test

### PR DESCRIPTION
**Pull request by coneiric**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Comment by coneiric** [comment]
Ok, I'll add some test cases for substitution failure (maybe turn SFINAE to SFIAE :smile: jk), and think about some other failure cases.

**Comment by anonimal** [comment]
>Ok, I'll add some test cases for substitution failure (maybe turn SFINAE to SFIAE smile jk)

Proper implementation of SFINAE requires adequate testing of said implementation. Assuming that an implementation fully implements SFINAE within the context of said implementation, because the standard library says "do this for SFINAE", does not equate to a proper implementation of SFINAE.

More importantly, because we have no policy for SFINAE, "expected exceptions and/or expected failures" should be tested, regardless, so as to allow malleable implementations. This is the core concept of a unit-test: to cover any and all pertinent aspects of a unit.

**Comment by coneiric** [comment]
> More importantly, because we have no policy for SFINAE, "expected exceptions and/or expected failures" should be tested

I'll do my best to test the expected exception/failure cases. Currently having some trouble getting the tests to work properly, but that should be resolved fairly soon. Apparently, I forgot to include the new test in the unit-test CMake file, and these tests were never ran. I've included it now, and am working on fixing the errors in my tests.

**Comment by coneiric** [comment]
>  working on fixing the errors in my tests

Apparently Boost macros hate templates with multiple arguments (the commas...). This gotcha set me back a few hours, but I used type aliases as a work-around. I tried `BOOST_PP_COMMA()` with no luck. If you have a better solution than my (somewhat) gross hack, I'm open to suggestions.

**Comment by coneiric** [comment]
> After you fix the i686 build (remember, boost 1.58), let's consider this PR resolved for now.

Fixing it now, didn't realize `BOOST_TEST` wasn't defined in 1.58.

**Pull request merged**
