### PR TITLE
Packager: add bash completion script for kovri

### PR DESCRIPTION
**Pull request by rakhimov**
This is a script for kovri command-line completion.
It's nice to have for packaging,
relevant to issue #362.

Adopted from [SCRAM](https://github.com/rakhimov/scram)

---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Comment by anonimal** [comment]
Other solutions are welcome too.

**Comment by rakhimov** [comment]
@anonimal I agree it is a nasty approach to hardcode and keep in sink.
It would be nice to find "single source of truth" for options and their argument types.
Unfortunately, Boost does not expose argument types (or possible values) by default;
it needs some manual code with 'value_type' and custom conventions for types.

The hardcoding can be swapped with the following code:
```bash
-*)
      (kovri --help | grep -q -E -- "${prev}.*\sarg\s") && return
      ;;
```
But again, it is not possible to deduce what to suggest.
Is it a file directory, string, number, boolean?

Note that the hardcoding is only for argument suggestion (i.e., not the completion/deduction),
so if options are added or changed, nothing really breaks.

**Comment by anonimal** [comment]
>(kovri --help | grep -q -E -- "${prev}.*\sarg\s") && return
>But again, it is not possible to deduce what to suggest.
Is it a file directory, string, number, boolean?

If we *really* wanted to keep `COMPREPLY`, maybe this is where a config file addendum could come in (alla quasi-INI):

```
# [String]

# comment = "This is log-level description, etc."
# option = "0 1 2 3 4 5"
log-level = 3

# comment = "This is port help"
port = 12345

# [Bool]

# comment = "This is enable-ssu description, etc."
# option = "on off yes no true false 1 0"
enable-ssu = 1
```

and then adjust the script to parse as needed. Syntax being flexible. Would this be worth the effort?

> so if options are added or changed, nothing really breaks.

Indeed, but I still think we should avoid any future potential dead code when possible.

**Comment by rakhimov** [comment]
Extra info in conf will help,
but now you have the same problem of keeping Boost options and conf options in sync.

Why not autogenerate the conf example from Boost (or vice versa)?
(or be implicit about it and document the association between cmd options and config vars)

This could be done by adding help-info into Boost options and consistently specifying their type in code
with value_name,
so the following pattern would be expected:
```bash
--option type  (=default) description
```
The type could be 'path, string, int, float'.

**Comment by rakhimov** [comment]
This duplication issue may come up again with man pages as well.

**Comment by anonimal** [comment]
Ok. How about we merge what we have so far and open a new issue that will tackle the issues above? If so, will you open the new issue after I merge?

**Comment by rakhimov** [comment]
@anonimal Sure, I will.

**Comment by anonimal** [comment]
Two sidenotes:

1. If this is to make it into the binary distribution or even `make install`, the installers will need to know of this file. We should also put a little note in documentation because end-users may not know of the purpose of this script (and then get confused when they see it).

2. The script should be set executable.

**Comment by rakhimov** [comment]
I don't think the script must be executable.
The completion scripts of other packages in /usr/share/bash-completion/completions don't have such property.
It may cause packaging issues.

**Comment by anonimal** [comment]
>I don't think the script must be executable.

Sorry! I was completely distracted and not thinking. That is correct.

**Pull request merged**
