### PR TITLE
Core: use IPv6 address object when expected + add test cases

### LINKED ISSUE #840: RouterInfo: ensure return of ipv6-capable Address object when requested
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

As noted by my [hasty typo](https://github.com/monero-project/kovri/blob/8b435571eb374c96fd6a3b2070a3c42cb66dc6d9/src/core/router/info.cc#L971), this should've been a TODO:

- An RI should **always** have an IPv4 address. Checks for that shouldn't be done here: assertions should / should eventually be in place for that elsewhere.
- The check *assumes* that the first iteration of Addresses will be ipv6. **It's not safe to assume**.

Referencing #627.

### PR DESCRIPTION
**Pull request by anonimal**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

Resolves #840.

Note: this PR decided to side-step most of the pre-fork issues mentioned in https://github.com/monero-project/kovri/issues/840#issuecomment-406165876 in favor of resolving a few immediate ones (including the adjusting of appropriate SSU packet size).

### CODE REVIEW

**Comment by anonimal** [comment]
Referencing #140.

**Comment by anonimal** [comment]
The tests' build only fails on machines that run old/stupidly old boost versions because of a boost bug. As you can also tell, the boost bug was fixed in recent versions.

Because of the abysmal state of https://github.com/monero-project/meta/issues/252 and the general backend issues that have plagued Monero Project for years, I'm at a point where I really just don't care anymore. If someone wants me to care, speak up. Otherwise I'll assume I'm talking into a black hole.

The tests build fine and pass on sane systems, as do the live tests. This PR can be merged before the code freeze.

**Comment by danrmiller** [comment]
What version of boost is required for kovri? For monero it's 1.58.

**Comment by SRCoughlin** [comment]
Kovri also requires 1.58.

**Pull request merged**
