### PR TITLE
Kovri: remove i2pd's endian, replace with ByteStream + Boost.Endian

### LINKED ISSUE #772: Core: throw out i2p_endian/little_big_endian, reimplement with Boost.Endian
---
**By submitting this issue, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.
---

As somewhat mentioned in the TODOs noted in #771, I ultimately want to get rid of all the i2p_endian/little_big_endian garbage and replace with a simple boost implementation.

### PR DESCRIPTION
**Pull request by anonimal**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

Resolves #772. References #140. Referencing #511 #643 among others (see the TODOs).

### CODE REVIEW

**Comment by anonimal** [comment]
Live tests and unit-tests pass on BE and LE machines (tested on Linux/FreeBSD/Windows).

**Comment by anonimal** [comment]
OpenBSD and OS X apparently want to `/usr/local/include/boost/endian/conversion.hpp:298:12: error: call to 'endian_reverse' is ambiguous`. Resolve before merging.

**Comment by coneiric** [comment]
Great changes. 

From what I've found so far, it looks like the ambiguous call error may be coming from the templated [Read](https://github.com/monero-project/kovri/pull/809/commits/dea57f7d937a6ebcd8ef1cd29f59e7bc7f51056f#diff-be8f17ffb33292655ec607648ea27d86R134) and [Write](https://github.com/monero-project/kovri/pull/809/commits/dea57f7d937a6ebcd8ef1cd29f59e7bc7f51056f#diff-be8f17ffb33292655ec607648ea27d86R171) functions.

There are multiple `endian_reverse` overloads for `uintNN_t`, which gets called by `boost::endian::native_to_big_inplace()` on little-endian machines.

Not sure what the right solution would be.

Maybe replacing:
```
if (native_to_big)
  boost::endian::native_to_big_inplace(data);
```
with
```
if (native_to_big)
  boost::endian::native_to_big_inplace(std::static_cast<decltype(data)>(data));
```
Then perhaps doing something similar for `Read()`, and other places where the `boost::endian::{native_to_big*,big_to_native*}` is passed a templated param?

**Comment by anonimal** [comment]
>Not sure what the right solution would be.

The build failures exposed pre-existing kovri type issues. I've fixed those issues and now the build is resolved (casting is not the way to resolve the issue).

**Comment by anonimal** [comment]
Note: OSX `router.info` looks good, as expected, but Linux is producing a bad `router.info` (introduced before aforementioned patch in previous comment). Hold on merging until I resolve the issue.

**Pull request merged**
