### PR TITLE
Style: Clarify deviations from the GCSG

### PR DESCRIPTION
**Pull request by rakhimov**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
- I am not basing this pull-request on branch ```master```
- I am sending this pull-request to branch ```development```

*Place an X inside the bracket (or click the box in preview) to confirm*
- [x] I confirm.

---

Corresponding configurations for clang-format are provided.
These deviations are tentative
as observed from the current state of the codebase.

Note that the observed deviations are not
from the core, contributing developer or author,
so many deviations or implicit conventions may be missing.
It is best to get this information
from people who actually wrote the code.

This commit addresses issue #238.

---
This change is [Reviewable](https://reviewable.io/reviews/monero-project/kovri/245)

### CODE REVIEW

**Comment by anonimal** [comment]
> Note that the observed deviations are not
from the core, contributing developer or author,
so many deviations or implicit conventions may be missing.
It is best to get this information
from people who actually wrote the code.

Can you clarify these statements? They are either misinformed or are being misread.

**Comment by rakhimov** [comment]
The conventions and rules are best to be written by the original owners/authors of the code.
For example, Linus writes the core coding style for Linux,
not some outsider who is taking a look at it.

**Comment by anonimal** [comment]
Your opinion is noted, but the truth is that such an idea is false - and is not how open source works. No one can simultaneously claim and retain authority of a language or interpretation; that defies the intrinsics of all communication. Language is ever-evolving, ever-impressionable, and there is no static-state to lay claim to.

Now, a simpler, more binary response: Debian does not own Ubuntu. Oracle does not own MariaDB. All authors of Kovri code (including myself, of which you've chosen to ignore) do not own the C++ language nor do we own any single writing style.

A functional, improved style was agreed upon *by the community* after we forked. It is something that we *try* to agree upon as a consensus; not as an authority. What we were forced to deal with before our agreement was an incomprehensible, unmaintainable mess of glorified C.

With that said, as you are now a new member to the community, you can influence what you perceive the style should be. This style may very well be an overall improvement and is welcomed - and **That** is the essence of open source.

I love Linus' work and have followed it intermittently since the 90's; but we all know that his opinion is nothing more than an opinion; as is yours; and as is mine.

**Comment by rakhimov** [comment]
@anonimal What I don't like is to waste time on style wars. There are so many opinions, experience levels, tastes, etc.
The main benefit of a coding style is to have one for our brains to work on patterns,
and I really don't mind if the project owner or owners (who wrote the code?) decide on something
because these folks are the ones who will stick around and maintain the majority of the code.

Kovri is an interesting case as a fork project though.
I really think it is good you folks chose the very-thorough GCSG.
My suggestion is to go all the way and embrace it. Drop all the format-specific deviations. Stop fighting Clang-Format.
Pass-through all the code through the modernizer, formatters to avoid manual labor.

**Comment by rakhimov** [comment]
Just to be clear. In my original statement, I didn't mean ``i2pd`` or ``orignal`` as the source of coding conventions. Probably that was the ambiguity I didn't pay attention to. (Politics sucks.)

**Comment by anonimal** [comment]
@rakhimov thank you for clarifying. There has been much distress on I2P side over the past year because of i2pd's actions. We've all been able to recover after the incident but when something like style arguments pop-up, it's like revisiting the past. Also, even after the fork, there have been some very troubling incidents so, things have been a bit touchy lately.

I've never claimed to fight against clang-format nor any formatting tool. Though I **don't** believe in becoming an automaton and I **do** believe in code artistry (of which has given way to certain style idioms (the only remaining human element)), I certainly don't want to fight automation for code style; especially given our current state of the project (we have more things to concern ourselves with)!

For me and this project, the problem has been mostly time; whether it be refactoring or devising and uncrustify configuration. The fact that you're producing actual code results along with ideas is encouraging so please continue to do that but do understand that, because of its past, kovri is no ordinary project.

Ultimately, I look forward to the past being nothing more than the past :smile:

**Comment by anonimal** [comment]
Also, you're always welcome to hangout in ```#kovri-dev``` on Irc2P or Freenode. If you use Slack, https://monero.slack.com (we've only recently set this up so it's not yet official, but it works well).

**Pull request merged**
