### PR TITLE
Add consts in various places where it makes sense

### PR DESCRIPTION
**Pull request by selene-kovri**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [ ] I confirm.

---

*Enter your pull-request summary here*

### CODE REVIEW

**Comment by selene-kovri** [comment]
Understood, I will work more on this to use the const versions of those two.

**Comment by anonimal** [comment]
Hi @selene-kovri, how is this coming along? Running into any snags?

**Comment by anonimal** [comment]
@selene-kovri I'm going to merge this now. If the dead code lingers we'll just remove it or refactor. You're still welcome to PR new/continuing work though.

**Comment by selene-kovri** [comment]
Thanks, and sorry I've not been able to work on this yet. Not much time :)

**Comment by selene-kovri** [comment]
I have looked some more, and I need an opinion on which path to take.
In order to use the const GetAddress/GetAddressBook functions, CheckAddressIdentHashFound and GetLoadedAddressIdentHash ought to be const. However, GetLoadedAddressIdentHash calls LoadSubscriptionFromPublisher, which is plainly non-const, even though the first two are logically const, and the loading does lazy loading of data.
One way to do this is to have a new function EnsureSubscriptionFromPublisherLoaded (which would be const) and make the loaded data mutable (I've not looked yet at exactly what would need to be mutable). I'm asking because having mutable data might be something that's unwanted (there's very little mutable use in the source).

**Comment by anonimal** [comment]
>GetLoadedAddressIdentHash calls LoadSubscriptionFromPublisher

Ideally, `LoadSubscriptionFromPublisher` should not be called from `GetLoadedAddressIdentHash` because the checking of ident hash should not rely on the ensuring of a subscription being loaded - as that is done within the addressbook's `SubscriberUpdateTimer`. What we do now is a hack to work around the original hacked design that we forked from - but - what *we* do will ensure that a subscription is loaded *before* the timer begins (because client tunnels are brought up on startup).

>I'm asking because having mutable data might be something that's unwanted (there's very little mutable use in the source).

I think the issue is endemic of design and could be resolved by decoupling the aforementioned *without* the need for enforcing `mutable` members (this decoupling work was put on the backburner but you're more than welcome to work on it).

Regarding both points: there are more chicken-or-the-egg design issues, one more being subscription download as done in `LoadSubscriptionFromPublisher`. If needed, I can give details in IRC if you decide to move forward on any of these issues.

**Pull request merged**
