### PR TITLE
Testnet: create named pipes for log output + refactor RI and container creation + logic layout refactor

### PR DESCRIPTION
**Pull request by anonimal**
@MoroccanMalinois let's hold on merging until we figure out why docker appears to not auto-flush the pipe (docker appears to only flush once the instance is stopped).

Note: #706 confirms that auto-flushing works (at least on mainnet).

---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Comment by MoroccanMalinois** [comment]
@anonimal  I don't think it's docker related. I'm getting the same behavior directly on the host.
Maybe i'm missing something. Here is how i tested:

    mkfifo test
    tail -f test

On another terminal

    cat LICENSE.md > test

The first time i run `cat`, i only see the last ~10 lines.
All the next time, i see all the file. 
Same for testnet, after a second start, logs are auto flushed (assuming `tail` stayed open between the runs).

**Comment by anonimal** [comment]
>I'm getting the same behavior directly on the host.

What's your host? I can only reproduce your issue on FreeBSD and MSYS2 (MSYS2 looks stupidly broken); I can't reproduce your issue on Arch, Ubuntu, or OSX (kovri auto-flushing to pipe also works as expected on these systems).

On my Arch docker host, creating/tailing the pipe + cat'ing big file into the pipe *within* the container works as well.  I don't think docker is completely innocent here.

**Comment by MoroccanMalinois** [comment]
My host is a debian jessie (not updated). Going to install and test a fresh stretch.

**Comment by MoroccanMalinois** [comment]
Tested with debian stretch, ubuntu 16.04 and (fedora-23 in Qubes). All the same.

**Comment by anonimal** [comment]
@MoroccanMalinois then let's not use tail. `cat`'ing the pipe works fine (I imagine that tail is blocking). Have you tried `s/tail -f/cat/` on your affected systems?

**Comment by anonimal** [comment]
Note: rebased some trivial changes not related to this PR discussion, also added 34a55a5 to save opening a new PR.

**Pull request merged**
