### PR TITLE
Contrib: Add tmoravec's PGP key

### PR DESCRIPTION
**Pull request by tmoravec**
anonimal on IRC writes:
>tmoravec: while you're here, since you've been sending in work repeatedly, you're welcome to submit your GPG key to kovri/contrib/pgp and `git commit -S` your commits if you'd like.

Thanks, submitting.

---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Comment by anonimal** [comment]
It will help if you sign this commit using the attached key :grin:

**Comment by tmoravec** [comment]
Lol, I'm dumb :) . Sorry, fixed.

**Comment by anonimal** [comment]
>Sorry, fixed.

I still don't see the commit signed with `$ git log --show-signature`. Does yout `.git/config` have something like this (and did you `$ git commit -S -i master`)?:

```
[user]
        email = moravec.tadeas@gmail.com
        name = tmoravec
        signingkey = 94FA7B49
```

**Comment by tmoravec** [comment]
Yet another attempt pushed. I was using `-s` (not capital S) all the time. I'm terribly sorry for taking your time with this.

**Pull request merged**
