### PR TITLE
Crypto: implement TweetNaCl via Crypto++, remove SUPERCOP (ref10) 

### LINKED ISSUE #345: Crypto: upgrade to supercop to latest release
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.

---

https://bench.cr.yp.to/supercop.html

### LINKED ISSUE #485: Swapout ref10 from SUPERCOP with TweetNaCl
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

The use of TweetNaCl has been discussed in the kovri meeting and several times in monero's meetings. Any objections or discussion should be noted in this issue.

**Edit**: ~~An incredibly easy thing to do~~, *Theoretically*, an incredibly easy thing to do **but**, as it turns out, implementation-wise, will require far more work because of how we use polymorphism for all verifying + signing (and a few other issues).

**Edit**: my personal *meh* moment is the amount of work to implement versus the trade-off benefits - but I do like the audit-ability factor. Also, closing this issue will resolve #345 and we also wouldn't need to use cryptopp for hashing (so that's a plus). For now, I'll unassign myself but will most likely be the one that gets to this - though @olarks has expressed an interest so I encourage more developers to get involved.

**Edit**: Note: this is still only a proposal. Does @fluffypony @EinMByte @luigi1111 @moneromooo-monero @hyc @NanoAkron @vtnerd @rakhimov @olarks or anyone else have any input on the issue?

### PR DESCRIPTION
**Pull request by anonimal**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

See git-log for details. References anonimal/cryptopp@caa06bf and #784. Resolves #485. Closes #345.

### CODE REVIEW

**Comment by anonimal** [comment]
Unit test passes. Live test fires an assertion.

**Comment by coneiric** [comment]
Just ran this branch in the Docker testnet, and Kovri exited with the following errors:

```
[2018.06.26 23:03:48.636067] [0x00007fc0af0a0440] [info]    The Kovri I2P Router Project
[2018.06.26 23:03:48.636154] [0x00007fc0af0a0440] [info]    0.1.0-pre-alpha-  "In the beginning"
[2018.06.26 23:03:48.636363] [0x00007fc0af0a0440] [info]    DaemonSingleton: configured
kovri: /home/kovri/kovri/src/core/crypto/impl/cryptopp/signature.cc:846: bool kovri::core::Ed25519Verifier::Ed25519VerifierImpl::Verify(const uint8_t*, std::size_t, const uint8_t*) const: Assertion `rmlen == sm.size()' failed.
[2018.06.26 23:09:12.322998] [0x00007f0b2ee11440] [info]    The Kovri I2P Router Project
[2018.06.26 23:09:12.323090] [0x00007f0b2ee11440] [info]    0.1.0-pre-alpha-  "In the beginning"
[2018.06.26 23:09:12.323325] [0x00007f0b2ee11440] [info]    DaemonSingleton: configured
kovri: /home/kovri/kovri/src/core/crypto/impl/cryptopp/signature.cc:846: bool kovri::core::Ed25519Verifier::Ed25519VerifierImpl::Verify(const uint8_t*, std::size_t, const uint8_t*) const: Assertion `rmlen == sm.size()' failed.
```

Tracking down the cause of the assertion firing, but wanted to leave this here in case it's helpful.

**Comment by coneiric** [comment]
Just made a PR to your branch, [anonimal/kovri#4](https://github.com/anonimal/kovri/pull/4) with updates that resolves the failed assertion.

After applying those patches, rebasing on current master, and resolving some merge conflicts, this branch passes all the live tests.

I was able to connect to a server tunnel, and use the IRC + HTTP proxies.

Everything looks good to me, unless there was another client destination test you ran that was failing.

**Comment by anonimal** [comment]
Live tests pass. This PR should be ready to merge.

Thank you very much to @noloader for his assistance in https://github.com/weidai11/cryptopp/pull/668. I've credited him in the git log.

**Pull request merged**
