### PR TITLE
MTUCHECK :: fix CID146758

### PR DESCRIPTION
**Pull request by guzzijones**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [x] I confirm.

---

*Enter your pull-request summary here*
This fixed CID 146759.  Will also work on refactoring this old c style code.

### CODE REVIEW

**Comment by anonimal** [comment]
From `strncpy()`:

>if src contains more than buflen - 1 bytes, information is lost in the copying to dest.)

So, bad news for long interface names.

>Will also work on refactoring this old c style code.

Good. `mtu.cc` is basically C because we're relying on the `if` family for *nix.

In the meantime, a patch to consider before merging:
```c
// Because IFNAMSIZ = sizeof(ifr.ifr_name)
strncpy(ifr.ifr_name, ifa->ifa_name, sizeof(ifr.ifr_name));
ifr.ifr_name[sizeof(ifr.ifr_name) - 1] = '\0';
```

**Comment by anonimal** [comment]
Also, I didn't complain about `strncpy()` because you said you're working on a refactor but, JFTR: `strncpy()` is outdated and should be avoided at all costs.

**Comment by guzzijones** [comment]
yes i need to investigate all of this code and refactor it.
For now I will update with your patch.
Thanks.

**Comment by guzzijones** [comment]
I am going to start studying this branch of the code.
Once I have a good grasp of what ntcp.* does and the downstream code i 
will start refactoring it with modern c++/boost code.

**Comment by anonimal** [comment]
Referencing #263 #333

**Pull request merged**
