### PR TITLE
I2NP: resolve namespace TODO + message type trivial style refactor

### PR DESCRIPTION
**Pull request by olarks**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [ X] I confirm.

---

*Enter your pull-request summary here*

### CODE REVIEW

**Comment by olarks** [comment]
@anonimal: Would there be any value in putting those values in seperate enum structs? I wanted to document those values anyway and would rather not undo those name stylings. Unless we are going to stick with the ALL_CAPS variable names. ALL_CAPS was used in other files as well that I was going to refactor as well in the future, but if we are going to stick with ALL_CAPS for those values and we don't want them in an enum struct then I won't refactor those files(I can still document them) to keep all the name styling consistent throughout the codebase.

**Comment by olarks** [comment]
The SSU refactor did put all those values into enum structs, but I guess it depends if we want static_casts all over the place.

**Comment by olarks** [comment]
I could also just close the PR and reopen in the future once I have more I2NP refactoring done. I just figured I would get the styling done first and then comb over the code.

**Comment by anonimal** [comment]
I'll repeat again what I said in IRC:

```
&anonimal       The question is not so much how it's contained nor how pretty it is, the question is more of how they are used. I keep saying see SSU refactor because that's how they should be handled.
&anonimal       That type of math for i2np should not be implemented there.
&anonimal       But these constants tie into bigger design changes so they are really just the toes on the leg that needs surgery; that's why I keep suggesting you consider other areas of work for now.
```

The design issue I keep speaking about (which was better resolved in the SSU refactor) has *nothing* to do with enum struct: `&anonimal       That type of math for i2np should not be implemented there.`

We should merge the TODO resolution though so please see my original comment/request.

**Comment by olarks** [comment]
I realize that and I understand what you are getting at, I have looked at the SSU refactor. I'll fix this PR so it only contains the namespace refactor. Thanks.

**Comment by olarks** [comment]
anonimal: Only the namespace refactor now ;)

**Comment by anonimal** [comment]
@olarks please rebase against new HEAD

**Pull request closed without merging**
