### PR TITLE
Coverety :: see #263 ; fixes CID #135927

### PR DESCRIPTION
**Pull request by guzzijones**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [x ] I confirm.

---

*Enter your pull-request summary here*
simply commented the code out for now

### CODE REVIEW

**Comment by anonimal** [comment]
```
&anonimal | guzzi: thanks for the new PR. Two issues though:
&anonimal | 1) that's upstream code; so any changes should be made upstream
&anonimal | 2) though the logic is correct, it looks like a false positive because of the crypto
&anonimal | guzzi: so, pending a 2nd opinion from EinMByte, I would recommend closing the PR and taking the issue upstream
```
@guzzijones @EinMByte

**Comment by guzzijones** [comment]
Ok i will close it and note upstream in coverity so at least we know we 
looked at it

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 11 de septiembre de 2016 4:59:58 PM 0x914409F1 
<notifications@github.com> escribio:

**Comment by guzzijones** [comment]
Anything in crypto is upstream right?

Enviado con Aquamail para Android
http://www.aqua-mail.com


El 11 de septiembre de 2016 4:59:58 PM 0x914409F1 
<notifications@github.com> escribio:

**Comment by anonimal** [comment]
>Anything in crypto is upstream right?

No, only most of what's in `supercop/ed25519` and everything in `/deps/`

**Pull request closed without merging**
