### PR TITLE
Build: fix ARMv7/8 builds. Fixes #384, refs #285

### LINKED ISSUE #384: Build: support ARMv7 + ARMv8
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [X] I confirm.
---

ARM support will at least require different cmake flags for both kovri and cryptopp. I don't have ARM machines to play so I can't personally ensure ARM support or run-time functionality.

For AES-NI run-time detection, I'm certain we'll have to fallback to library support instead of using our native impl (see #285).

Current build logs:
https://build.getmonero.org/builders/kovri-all-ubuntu-arm7/builds/0/
https://build.getmonero.org/builders/kovri-all-ubuntu-arm8/builds/0

### PR DESCRIPTION
**Pull request by anonimal**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [X] I confirm.

---

- Fixes CMake for ARM, add compile-time patches for run-time AES-NI
- Preprocessor: also added MSVS macro for future MSVS testing
- Cleaned-up CMake / shared hardening flags with Clang

### CODE REVIEW

**Comment by anonimal** [comment]
Hi @danrmiller, the [armv8 build](https://build.getmonero.org/builders/kovri-all-linux-arm8/builds/5/steps/compile/logs/stdio) needs miniupnpc.

**Comment by NanoAkron** [comment]
Have you seen how we detect arm and crypto options in monero'a CMakeLists.txt?

I know asking the compiler isn't ideal, but even the guys behind MBED find it hard to properly define the target architecture because AFAIK for some reason ARM keeps the internal options register protected

**Comment by anonimal** [comment]
@NanoAkron yes but I'm not sure how that's relevant now (crypto impl is currently handled by external libraries).  What exactly do you mean? Lib-side compiler fine tuning can come later - after we get the builds running (or if someone else wants to get involved now).

**Comment by anonimal** [comment]
ARMv8 build is currently failing because of `No space left on device`. pigeons and host provider are currently working on a fix.

**Pull request merged**
