### PR TITLE
Configure clang with gcc 4.9 on Travis-CI

### PR DESCRIPTION
**Pull request by rakhimov**
**By submitting this pull-request, I confirm the following:**

- I have read and understood the [Contributing Guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.

*Place an X inside the bracket (or click the box in preview) to confirm*
- [x] I confirm.

---

---
This change is [Reviewable](https://reviewable.io/reviews/monero-project/kovri/289)

### CODE REVIEW

**Comment by anonimal** [comment]
Referencing #277.

@rakhimov in the future, could you [please try to not mix formatting fixes with non-formatting commits](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md)? Thanks.

**Comment by rakhimov** [comment]
The config was such a mess couldn't help myself.

**Comment by anonimal** [comment]
lol, I know that feeling :smile:

IIRC, ```$ travis lint``` (or one of the travis commands) used to auto-format the config. The last time the config was linted or ran through the gem, that output was the result; so I learned to deal with it.

**Comment by rakhimov** [comment]
``travis encrypt secret --add`` is the prime suspect :smile:

**Pull request merged**
