### PR TITLE
Add bash-completion to contrib

### PR DESCRIPTION
**Pull request by chris-barry**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the contributor guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Comment by chris-barry** [comment]
I see some tests are failing. Since I changed no code, I find it likely this existed before my PR.

**Comment by anonimal** [comment]
Have you not seen our [existing bash completion script](https://github.com/monero-project/kovri/blob/master/pkg/kovri-bash.sh)?

**Comment by chris-barry** [comment]
Oh jeez, I did not D: thank you for alerting me

**Comment by anonimal** [comment]
No problem. I think you're correct though to have looked in `contrib` first. We should probably move the completion script there and symlink to the package directory so we can continue packaging the script.  Care to open a PR for that?

**Pull request closed without merging**
