### PR TITLE
Added dependency list for Fedora

### PR DESCRIPTION
**Pull request by shmacoshmuesday**
---
**By submitting this pull-request, I confirm the following:**

- I have read and understood the developer guide in [kovri-docs](https://github.com/monero-project/kovri-docs).
- I have checked that another pull-request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull-request may be closed by the will of the maintainer.
- I give this submission freely under the BSD 3-clause license.
---

### CODE REVIEW

**Review by coneiric — COMMENTED** [review]
Change formatting and content looks good, thanks for the contribution.

I'm not sure how many flavors of Linux we want to display dependencies for, though.

**Review by anonimal — CHANGES_REQUESTED** [review]
Hi @shmacoshmuesday. Please `$ git rebase -i master` and `fixup` the most recent commit so we only have 1 commit to merge. Thanks.

**Comment by anonimal** [comment]
Oh, that's assuming you were using a topic branch, which you aren't. You can try something like `$ git rebase -i HEAD~2` instead.

**Comment by anonimal** [comment]
NOTICE: THIS PULL REQUEST HAS BEEN MOVED TO GitLab. Please reopen there if you wish to merge. See https://github.com/monero-project/kovri/issues/1013 for details.

**Comment by shmacoshmuesday** [comment]
Sorry for my late response, and thanks for the instructions anonimal. I'll checkout gitlab and submit again, though it may take a while simply because I have a lot of things competing for my time most of the time. Thanks for all you do anonimal and coneiric!

**Pull request closed without merging**
