### PR TITLE
Docs: change links to cpplint project

### PR DESCRIPTION
**Pull request by rakhimov**
**By submitting this pull request, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that another pull request for this purpose does not exist.
- I have considered and confirmed that this submission will be valuable to others.
- I accept that this submission may not be used and that this pull request may be closed by the will of the maintainer.
- I give this submission freely under BSD-3 license.

*Place an X inside the bracket to confirm*
- [x] I confirm.

---

*Enter your pull request summary here*

Cpplint is now provided as a Python module with extra features
thanks to https://github.com/theandrewdavis/cpplint

---
This change is [Reviewable](https://reviewable.io/reviews/monero-project/kovri/230)

### CODE REVIEW

**Comment by rakhimov** [comment]
Hi folks,
```
... claim no ownership to its content
```
doesn't make sense.
Please consult with some decent CLA (harmony, apache, google).

**Comment by anonimal** [comment]
Thank you @rakhimov for the updates.

Re: ```claim no ownership to its content```, this came up in discussion between myself and @fluffypony a little while ago and I think this should be revisited. I agree with your change. Could you open a new issue so we can come to a permanent resolution (then we can address the GitHub template)?

**Comment by anonimal** [comment]
Also, if you could please close this PR and reopen to branch development (per [contributing guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md)), that would help us alot. We're still debating whether to keep branch development (but, for now, thank you in advance).

**Comment by rakhimov** [comment]
Ups, that was a slip.

**Pull request closed without merging**
